version: "3"

services:
  lease-node0-db:
    image: postgres:14.9-alpine3.18
    container_name: lease-node0-db
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.4
    volumes:
      - ~/docker/data/node0:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--lc-collate=c.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      - POSTGRES_USER=postchain
      - POSTGRES_PASSWORD=postchain
    ports:
      - "127.0.0.1:5440:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  lease-node1-db:
    image: postgres:14.9-alpine3.18
    container_name: lease-node1-db
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.5
    volumes:
      - ~/docker/data/node1:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--lc-collate=c.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      - POSTGRES_USER=postchain
      - POSTGRES_PASSWORD=postchain
    ports:
      - "127.0.0.1:5441:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  lease-node2-db:
    image: postgres:14.9-alpine3.18
    container_name: lease-node2-db
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.6
    volumes:
      - ~/docker/data/node2:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--lc-collate=c.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      - POSTGRES_USER=postchain
      - POSTGRES_PASSWORD=postchain
    ports:
      - "127.0.0.1:5442:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  lease-node3-db:
    image: postgres:14.9-alpine3.18
    container_name: lease-node3-db
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.7
    volumes:
      - ~/docker/data/node3:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--lc-collate=c.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      - POSTGRES_USER=postchain
      - POSTGRES_PASSWORD=postchain
    ports:
      - "127.0.0.1:5443:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  node0-cli:
    image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.13.0
    container_name: node0-cli
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.8
    ports:
      - "7730:7740"
      - "7750:7750"
    volumes:
      - ./:/usr/app
    command: chr node start -bc /usr/app/build/auo-contract.xml -np /usr/app/conf/node0.properties --wipe
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  node1-cli:
    image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.13.0
    container_name: node1-cli
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.9
    ports:
      - "7731:7740"
      - "7751:7750"
    volumes:
      - ./:/usr/app
    command: chr node start -bc /usr/app/build/auo-contract.xml -np /usr/app/conf/node1.properties --wipe
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  node2-cli:
    image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.13.0
    container_name: node2-cli
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.10
    ports:
      - "7732:7740"
      - "7752:7750"
    volumes:
      - ./:/usr/app
    command: chr node start -bc /usr/app/build/auo-contract.xml -np /usr/app/conf/node2.properties --wipe
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

  node3-cli:
    image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.13.0
    container_name: node3-cli
    networks:
      postchain-mainnet:
        ipv4_address: 172.31.0.11
    ports:
      - "7733:7740"
      - "7753:7750"
    volumes:
      - ./:/usr/app
    command: chr node start -bc /usr/app/build/auo-contract.xml -np /usr/app/conf/node3.properties --wipe
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

networks:
  postchain-mainnet:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
